### ISSUE TITLE
KeyError: 'transactions'

### ISSUE THREAD

**Issue by x1138633899** [lAmeR1/kaspa-db-filler#7]
2023-05-26 08:45:32,555::DEBUG::TxAddrMappingUpdater::Start TxAddrMappingUpdater
2023-05-26 08:45:32,593::DEBUG::kaspad.KaspadClient::Request end
2023-05-26 08:45:32,612::INFO::__main__::Start hash: 21b82b0b2c04a24c53674497d4fe11278133a9757e42757c5c7dbc592b859b5a
2023-05-26 08:45:32,612::DEBUG::kaspad.KaspadClient::Request start: getBlocksRequest, {'lowHash': '21b82b0b2c04a24c53674497d4fe11278133a9757e42757c5c7dbc592b859b5a', 'includeTransactions': True, 'includeBlocks': True}
2023-05-26 08:45:32,772::DEBUG::kaspad.KaspadClient::Request end
2023-05-26 08:45:32,772::DEBUG::kaspad.KaspadClient::Request start: getBlockDagInfoRequest, {}
2023-05-26 08:45:32,776::DEBUG::kaspad.KaspadClient::Request end
2023-05-26 08:45:32,776::ERROR::__main__::Exception occured and script crashed..
Traceback (most recent call last):
  File "/app/main.py", line 119, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 87, in main
    await bp.loop(start_hash)
  File "/app/BlocksProcessor.py", line 43, in loop
    await self.__add_tx_to_queue(block_hash, block)
  File "/app/BlocksProcessor.py", line 101, in __add_tx_to_queue
    for transaction in block["transactions"]:
KeyError: 'transactions'

blockhash: 21b82b0b2c04a24c53674497d4fe11278133a9757e42757c5c7dbc592b859b5a
<img width="1107" alt="image" src="https://github.com/lAmeR1/kaspa-db-filler/assets/73155982/aa840bc9-6c12-4b0b-92b7-49e130288ab1">
The requested data is returned null

**Comment by lAmeR1** [comment]
The problem is you have old block data, but no transactions for it, since they seem to be pruned already.

So you can't properly fill the TXs into database
